# create your drupal and postgres config here, based off the last assignment

version: '2'

services:
  server_db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - drupal-data:/var/lib/postgresql/data
  cms:
    image: custom-drupal
    build: .
    ports:
      - '80:80'
    depends_on:
      - server_db
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
