version: '2'

services:
  server_db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - server-db-data:/var/lib/postgresql/data
  cms:
    image: drupal:8.8.2
    ports:
      - '8080:80'
    depends_on:
      - server_db
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
volumes:
  server-db-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: